apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - image: kapatsyndianadockerid/orderservice
          name: orders
          ports:
            - containerPort: 8088
              name: orders
          env:
            - name: POSTGRES_ENDPOINT
              value: "jdbc:postgresql://192.168.1.2:5435/"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_USERNAME
              value: "postgres"